// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:ba8b39645db6dcdd999faf096d266d488f91020268ff570c045026b47d68cbb5'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:93467bebb15eea7f4910ac06c5df723d68df8263416e197f9c13c3360c03e6ea'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly SheetConnection: {
      readonly clerkUserId: CodecTypes['pg/text@1']['output'];
      readonly apiKeyEncrypted: CodecTypes['pg/text@1']['output'];
      readonly apiKeyLastFour: CodecTypes['pg/text@1']['output'];
      readonly spreadsheetId: CodecTypes['pg/text@1']['output'];
      readonly worksheetName: CodecTypes['pg/text@1']['output'];
      readonly status: 'CONNECTED' | 'DISCONNECTED' | 'FAILED';
      readonly lastErrorCode: CodecTypes['pg/text@1']['output'] | null;
      readonly lastTestedAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly lastSyncAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly SheetConnection: {
      readonly clerkUserId: CodecTypes['pg/text@1']['input'];
      readonly apiKeyEncrypted: CodecTypes['pg/text@1']['input'];
      readonly apiKeyLastFour: CodecTypes['pg/text@1']['input'];
      readonly spreadsheetId: CodecTypes['pg/text@1']['input'];
      readonly worksheetName: CodecTypes['pg/text@1']['input'];
      readonly status: 'CONNECTED' | 'DISCONNECTED' | 'FAILED';
      readonly lastErrorCode: CodecTypes['pg/text@1']['input'] | null;
      readonly lastTestedAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly lastSyncAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly sheetConnection: {
      readonly apiKeyEncrypted: CodecTypes['pg/text@1']['output'];
      readonly apiKeyLastFour: CodecTypes['pg/text@1']['output'];
      readonly clerkUserId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly lastErrorCode: CodecTypes['pg/text@1']['output'] | null;
      readonly lastSyncAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly lastTestedAt: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly spreadsheetId: CodecTypes['pg/text@1']['output'];
      readonly status: 'CONNECTED' | 'DISCONNECTED' | 'FAILED';
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly worksheetName: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly sheetConnection: {
      readonly apiKeyEncrypted: CodecTypes['pg/text@1']['input'];
      readonly apiKeyLastFour: CodecTypes['pg/text@1']['input'];
      readonly clerkUserId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly lastErrorCode: CodecTypes['pg/text@1']['input'] | null;
      readonly lastSyncAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly lastTestedAt: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly spreadsheetId: CodecTypes['pg/text@1']['input'];
      readonly status: 'CONNECTED' | 'DISCONNECTED' | 'FAILED';
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly worksheetName: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly sheetConnection: {
              columns: {
                readonly clerkUserId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly apiKeyEncrypted: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly apiKeyLastFour: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly spreadsheetId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly worksheetName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'DISCONNECTED'>;
                  };
                };
                readonly lastErrorCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly lastTestedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: true;
                };
                readonly lastSyncAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['clerkUserId'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ConnectionStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['CONNECTED', 'DISCONNECTED', 'FAILED'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly sheetConnection: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SheetConnection';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly SheetConnection: {
            readonly fields: {
              readonly clerkUserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly apiKeyEncrypted: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly apiKeyLastFour: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly spreadsheetId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly worksheetName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastErrorCode: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastTestedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly lastSyncAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'sheetConnection';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly clerkUserId: { readonly column: 'clerkUserId' };
                readonly apiKeyEncrypted: { readonly column: 'apiKeyEncrypted' };
                readonly apiKeyLastFour: { readonly column: 'apiKeyLastFour' };
                readonly spreadsheetId: { readonly column: 'spreadsheetId' };
                readonly worksheetName: { readonly column: 'worksheetName' };
                readonly status: { readonly column: 'status' };
                readonly lastErrorCode: { readonly column: 'lastErrorCode' };
                readonly lastTestedAt: { readonly column: 'lastTestedAt' };
                readonly lastSyncAt: { readonly column: 'lastSyncAt' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly ConnectionStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'CONNECTED'; readonly value: 'CONNECTED' },
              { readonly name: 'DISCONNECTED'; readonly value: 'DISCONNECTED' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'sheetConnection';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
